---
version: "3"
services:
 devopsdb:
   image: poornapj/mynewimage:db
   ports:
     - "3306:3306"

 application:
   image: poornapj/mynewimage:appimage
   ports:
     - "9999:8080"
   depends_on:
     - "devopsdb"
